# Site settings
title: Kyle Robertson
baseurl: ""
url: "http://localhost:4000"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: 
disqus_shortname: 
